from __future__ import annotations

from typing import Any


MANUAL_JURISDICTION_OVERRIDES: dict[str, dict[str, Any]] = {
    "adrian-daily-telegram__1960-02-19": {
        "city_name": "Madison",
        "state_abbr": "MI",
        "jurisdiction_level": "township",
        "target_pid6": "167108",
        "note": "Ordinance title and enactment clause name Madison Township, Lenawee County, Michigan; current Census of Governments continuation is Charter Township of Madison.",
    },
    "benton-harbor-news-palladium__1971-02-09": {
        "city_name": "St Joseph",
        "state_abbr": "MI",
        "jurisdiction_level": "township",
        "target_pid6": "201929",
        "note": "Classifier evidence names Township of St. Joseph, Michigan; workbook candidate for Charter Township of St Joseph matches the governing unit, not Royalton Township.",
    },
    "bradentown-manatee-river-journal-and-herald__1923-12-27": {
        "city_name": "Bradenton",
        "state_abbr": "FL",
        "jurisdiction_level": "city",
        "target_pid6": "194764",
        "note": "Ordinance text uses historical spelling Bradentown; governing city is modern Bradenton.",
    },
    "charleroi-mail__1929-09-13": {
        "city_name": "North Charleroi",
        "state_abbr": "PA",
        "jurisdiction_level": "borough",
        "target_pid6": "112061",
        "note": "Header and enacting clause both spell North Charleroi; extraction string is OCR-corrupted.",
    },
    "canandaigua-daily-messenger__1965-11-03": {
        "city_name": "Bloomfield",
        "state_abbr": "NY",
        "jurisdiction_level": "village",
        "target_pid6": "170589",
        "note": "Ordinance text identifies the historical Village of Holcomb, New York. Holcomb merged with East Bloomfield in 1990 to form the present Village of Bloomfield.",
    },
    "canandaigua-daily-messenger__1965-09-16": {
        "city_name": "Gorham",
        "state_abbr": "NY",
        "jurisdiction_level": "town",
        "target_pid6": "170923",
        "note": "Clean ordinance text repeatedly identifies the Town of Gorham, New York. The classifier extraction dropped the h and incorrectly resolved to Gorman, Texas.",
    },
    "carrollton-chronicle__1947-01-31": {
        "city_name": "Carrollton",
        "state_abbr": "TX",
        "jurisdiction_level": "city",
        "target_pid6": "135130",
        "note": "Ordinance text places the governing city in Dallas County, Texas; extraction string Cartroiten is an OCR corruption of Carrollton.",
    },
    "daily-journal__1971-09-09": {
        "city_name": "Otter Tail",
        "state_abbr": "MN",
        "jurisdiction_level": "county",
        "target_pid6": "167374",
        "note": "Ordinance text repeatedly names Otter Tail County; extraction string has OCR corruption in Tail.",
    },
    "fayetteville-eagle-bulletin-and-dewitt-news-times__1967-08-17": {
        "city_name": "De Witt",
        "state_abbr": "NY",
        "jurisdiction_level": "town",
        "target_pid6": "186686",
        "note": "Classifier evidence names Town of DeWitt; Census of Governments uses spaced form De Witt.",
    },
    "fort-recovery-journal__1972-11-23": {
        "city_name": "Fort Recovery",
        "state_abbr": "OH",
        "jurisdiction_level": "village",
        "target_pid6": "209079",
        "note": "Ordinance text says Village of Ft. Recovery; override expands the common abbreviation.",
    },
    "fort-recovery-journal__1972-11-30": {
        "city_name": "Fort Recovery",
        "state_abbr": "OH",
        "jurisdiction_level": "village",
        "target_pid6": "209079",
        "note": "Ordinance text says Village of Ft. Recovery; override expands the common abbreviation.",
    },
    "guthrian__1972-06-19": {
        "city_name": "Guthrie",
        "state_abbr": "IA",
        "jurisdiction_level": "county",
        "target_pid6": "201753",
        "note": "Enactment clause identifies Guthrie County, Iowa.",
    },
    "humboldt-independent__1967-12-30": {
        "city_name": "Humboldt",
        "state_abbr": "IA",
        "jurisdiction_level": "county",
        "target_pid6": "126544",
        "note": "Enactment clause identifies Humboldt County, Iowa.",
    },
    "humboldt-republican__1967-12-27": {
        "city_name": "Humboldt",
        "state_abbr": "IA",
        "jurisdiction_level": "county",
        "target_pid6": "126544",
        "note": "Enactment clause identifies Humboldt County, Iowa.",
    },
    "holland-evening-sentinel__1976-09-14": {
        "city_name": "Holland",
        "state_abbr": "MI",
        "jurisdiction_level": "township",
        "target_pid6": "204703",
        "note": "Title and enacting clause explicitly identify Charter Township of Holland.",
    },
    "ironwood-daily-globe__1989-05-17": {
        "city_name": "Marenisco",
        "state_abbr": "MI",
        "jurisdiction_level": "township",
        "target_pid6": "166991",
        "note": "The enactment clause identifies Township of Marenisco, County of Gogebic, State of Michigan.",
    },
    "ironwood-daily-globe__1996-03-09": {
        "city_name": "McMillan",
        "state_abbr": "MI",
        "jurisdiction_level": "township",
        "target_pid6": "106562",
        "note": "Ordinance header identifies McMillan Township, Ontonagon County, Michigan.",
    },
    "kokomo-tribune__1982-12-01": {
        "city_name": "Russiaville",
        "state_abbr": "IN",
        "jurisdiction_level": "town",
        "target_pid6": "163558",
        "note": "Enacting clause spells Russiaville; extraction string is OCR-corrupted.",
    },
    "kokomo-tribune__1982-12-08": {
        "city_name": "Russiaville",
        "state_abbr": "IN",
        "jurisdiction_level": "town",
        "target_pid6": "163558",
        "note": "Enacting clause spells Russiaville; extraction string is OCR-corrupted.",
    },
    "ludington-daily-news__1977-06-11": {
        "city_name": "Pere Marquette",
        "state_abbr": "MI",
        "jurisdiction_level": "township",
        "target_pid6": "167146",
        "note": "Title and enacting clause explicitly identify Charter Township of Pere Marquette.",
    },
    "newport-daily-news__1972-01-14": {
        "city_name": "Portsmouth",
        "state_abbr": "RI",
        "jurisdiction_level": "town",
        "target_pid6": "209435",
        "note": "Title and amendment clause clearly say Portsmouth, Rhode Island; extraction string is OCR-corrupted.",
    },
    "red-bank-register__1954-05-06": {
        "city_name": "Colts Neck",
        "state_abbr": "NJ",
        "jurisdiction_level": "township",
        "target_pid6": "170313",
        "note": "Atlantic Township in Monmouth County is the historical name of present-day Colts Neck Township.",
    },
    "red-bank-register__1957-03-14": {
        "city_name": "Tinton Falls",
        "state_abbr": "NJ",
        "jurisdiction_level": "borough",
        "target_pid6": "109106",
        "note": "Borough of New Shrewsbury is the historical name of present-day Borough of Tinton Falls.",
    },
    "albion-evening-recorder__1954-09-17": {
        "city_name": "Sheridan",
        "state_abbr": "MI",
        "jurisdiction_level": "township",
        "target_pid6": "183997",
        "note": "Ordinance title and enactment clause identify Sheridan Township in Calhoun County, Michigan.",
    },
    "albion-evening-recorder__1959-06-19": {
        "city_name": "Sheridan",
        "state_abbr": "MI",
        "jurisdiction_level": "township",
        "target_pid6": "183997",
        "note": "Ordinance title and enactment clause identify Sheridan Township in Calhoun County, Michigan.",
    },
    "albion-evening-recorder__1968-12-19": {
        "city_name": "Clarence",
        "state_abbr": "MI",
        "jurisdiction_level": "township",
        "target_pid6": "128383",
        "note": "Title page states Township of Clarence, Calhoun County, Michigan.",
    },
    "albion-evening-recorder__1978-12-15": {
        "city_name": "Sheridan",
        "state_abbr": "MI",
        "jurisdiction_level": "township",
        "target_pid6": "183997",
        "note": "Ordinance title and enactment clause identify Sheridan Township in Calhoun County, Michigan.",
    },
    "amarillo-globe__1931-07-27": {
        "city_name": "Amarillo",
        "state_abbr": "TX",
        "jurisdiction_level": "city",
        "target_pid6": "194809",
        "note": "Ordinance text identifies the governing unit as the City of Amarillo, Texas.",
    },
    "amarillo-globe__1931-08-03": {
        "city_name": "Amarillo",
        "state_abbr": "TX",
        "jurisdiction_level": "city",
        "target_pid6": "194809",
        "note": "Ordinance text identifies the governing unit as the City of Amarillo, Texas.",
    },
    "austin-daily-herald__1976-02-03": {
        "city_name": "Austin",
        "state_abbr": "MN",
        "jurisdiction_level": "city",
        "target_pid6": "193555",
        "note": "Ordinance text identifies the Common Council of the City of Austin; the newspaper context is Austin, Minnesota.",
    },
    "bakersfield-californian__1957-06-29": {
        "city_name": "Kern",
        "state_abbr": "CA",
        "jurisdiction_level": "county",
        "target_pid6": "189634",
        "note": "Ordinance header identifies the Board of Supervisors of the County of Kern, State of California.",
    },
    "benton-harbor-news-palladium__1955-11-09": {
        "city_name": "Benton",
        "state_abbr": "MI",
        "jurisdiction_level": "township",
        "target_pid6": "166885",
        "note": "Ordinance title identifies Benton Township in Berrien County, Michigan; current Census of Governments continuation is Charter Township of Benton.",
    },
    "benton-harbor-news-palladium__1966-05-21": {
        "city_name": "Benton",
        "state_abbr": "MI",
        "jurisdiction_level": "township",
        "target_pid6": "166885",
        "note": "Ordinance title identifies Benton Township in Berrien County, Michigan; current Census of Governments continuation is Charter Township of Benton.",
    },
    "benton-harbor-herald-palladium__1975-02-21": {
        "city_name": "Sodus",
        "state_abbr": "MI",
        "jurisdiction_level": "township",
        "target_pid6": "128378",
        "note": "Enactment clause identifies Sodus Township; the county context is Berrien County, Michigan.",
    },
    "caribou-county-sun__1972-09-14": {
        "city_name": "Caribou",
        "state_abbr": "ID",
        "jurisdiction_level": "county",
        "target_pid6": "162020",
        "note": "Enactment clause identifies Caribou County, Idaho.",
    },
    "cedar-rapids-gazette__1981-08-15": {
        "city_name": "Linn",
        "state_abbr": "IA",
        "jurisdiction_level": "county",
        "target_pid6": "164259",
        "note": "Enactment clause identifies Linn County, Iowa.",
    },
    "chester-times__1925-12-17": {
        "city_name": "Prospect Park",
        "state_abbr": "PA",
        "jurisdiction_level": "borough",
        "target_pid6": "209244",
        "note": "Ordinance header identifies the Borough of Prospect Park; the Chester newspaper context is Delaware County, Pennsylvania.",
    },
    "chester-times__1927-10-10": {
        "city_name": "Norwood",
        "state_abbr": "PA",
        "jurisdiction_level": "borough",
        "target_pid6": "173936",
        "note": "Ordinance header identifies the Borough of Norwood, consistent with the Delaware County Chester newspaper context.",
    },
    "chester-times__1928-03-06": {
        "city_name": "Chester",
        "state_abbr": "PA",
        "jurisdiction_level": "city",
        "target_pid6": "173929",
        "note": "Ordinance header explicitly identifies the City of Chester, Pennsylvania.",
    },
    "chester-times__1945-11-20": {
        "city_name": "Tinicum",
        "state_abbr": "PA",
        "jurisdiction_level": "township",
        "target_pid6": "133755",
        "note": "Ordinance header identifies Tinicum Township; the Chester newspaper context places it in Delaware County, Pennsylvania.",
    },
    "clare-sentinel__1961-06-22": {
        "city_name": "Grant",
        "state_abbr": "MI",
        "jurisdiction_level": "township",
        "target_pid6": "166938",
        "note": "Ordinance title identifies Grant Township; the Clare newspaper context places it in Clare County, Michigan.",
    },
    "daily-globe__1968-11-04": {
        "city_name": "Ironwood",
        "state_abbr": "MI",
        "jurisdiction_level": "township",
        "target_pid6": "106482",
        "note": "Ordinance header identifies Ironwood Township, Gogebic County, Michigan; current Census of Governments continuation is Charter Township of Ironwood.",
    },
    "daily-globe__1971-10-29": {
        "city_name": "Ironwood",
        "state_abbr": "MI",
        "jurisdiction_level": "township",
        "target_pid6": "106482",
        "note": "Ordinance header identifies Ironwood Township, Gogebic County, Michigan; current Census of Governments continuation is Charter Township of Ironwood.",
    },
    "daily-globe__1996-03-09": {
        "city_name": "McMillan",
        "state_abbr": "MI",
        "jurisdiction_level": "township",
        "target_pid6": "106562",
        "note": "Ordinance header identifies McMillan Township, Ontonagon County, Michigan.",
    },
    "daily-journal__1965-11-20": {
        "city_name": "Fergus Falls",
        "state_abbr": "MN",
        "jurisdiction_level": "city",
        "target_pid6": "167581",
        "note": "Ordinance header identifies the City of Fergus Falls, Minnesota.",
    },
    "daily-telegram__1952-12-15": {
        "city_name": "Eau Claire",
        "state_abbr": "WI",
        "jurisdiction_level": "city",
        "target_pid6": "177137",
        "note": "Evidence quote identifies the City of Eau Claire; the newspaper context is Eau Claire, Wisconsin.",
    },
    "daily-telegram__1955-01-31": {
        "city_name": "Eau Claire",
        "state_abbr": "WI",
        "jurisdiction_level": "county",
        "target_pid6": "136503",
        "note": "Enactment clause identifies Eau Claire County, Wisconsin.",
    },
    "daily-telegram__1962-04-20": {
        "city_name": "Washington",
        "state_abbr": "WI",
        "jurisdiction_level": "town",
        "target_pid6": "209875",
        "note": "Ordinance title and enactment clause identify the Town of Washington, Eau Claire County, Wisconsin.",
    },
    "daily-telegram__1967-02-03": {
        "city_name": "Union",
        "state_abbr": "WI",
        "jurisdiction_level": "town",
        "target_pid6": "177431",
        "note": "Ordinance title and enactment clause identify the Town of Union, Eau Claire County, Wisconsin.",
    },
    "dubuque-telegraph-herald__1971-02-18": {
        "city_name": "Dubuque",
        "state_abbr": "IA",
        "jurisdiction_level": "county",
        "target_pid6": "193301",
        "note": "Ordinance title identifies Dubuque County, Iowa.",
    },
    "eau-claire-leader__1955-04-10": {
        "city_name": "Eau Claire",
        "state_abbr": "WI",
        "jurisdiction_level": "county",
        "target_pid6": "136503",
        "note": "Enactment clause identifies Eau Claire County, Wisconsin.",
    },
    "eau-claire-leader__1962-04-21": {
        "city_name": "Washington",
        "state_abbr": "WI",
        "jurisdiction_level": "town",
        "target_pid6": "209875",
        "note": "Ordinance title and enactment clause identify the Town of Washington, Eau Claire County, Wisconsin.",
    },
    "eau-claire-leader__1967-02-04": {
        "city_name": "Union",
        "state_abbr": "WI",
        "jurisdiction_level": "town",
        "target_pid6": "177431",
        "note": "Ordinance title and enactment clause identify the Town of Union, Eau Claire County, Wisconsin.",
    },
    "fergus-falls-daily-journal__1965-11-20": {
        "city_name": "Fergus Falls",
        "state_abbr": "MN",
        "jurisdiction_level": "city",
        "target_pid6": "167581",
        "note": "Ordinance header identifies the City of Fergus Falls, Minnesota.",
    },
    "fergus-falls-daily-journal__1971-09-09": {
        "city_name": "Otter Tail",
        "state_abbr": "MN",
        "jurisdiction_level": "county",
        "target_pid6": "167374",
        "note": "Enactment clause identifies Otter Tail County, Minnesota.",
    },
    "fergus-falls-daily-journal__1977-02-14": {
        "city_name": "Rothsay",
        "state_abbr": "MN",
        "jurisdiction_level": "city",
        "target_pid6": "106929",
        "note": "Ordinance text clearly identifies the City of Rothsay, Minnesota; extraction string is OCR-corrupted.",
    },
    "fond-du-lac-commonwealth-reporter__1966-01-17": {
        "city_name": "Auburn",
        "state_abbr": "WI",
        "jurisdiction_level": "town",
        "target_pid6": "177435",
        "note": "Enactment clause identifies the Town of Auburn, Fond du Lac County, Wisconsin.",
    },
    "harrison-clare-county-cleaver__1974-08-01": {
        "city_name": "Lincoln",
        "state_abbr": "MI",
        "jurisdiction_level": "township",
        "target_pid6": "128400",
        "note": "Ordinance text identifies Lincoln Township, Clare County, Michigan.",
    },
    "hillsdale-daily-news__1976-04-05": {
        "city_name": "Wheatland",
        "state_abbr": "MI",
        "jurisdiction_level": "township",
        "target_pid6": "167010",
        "note": "Ordinance text identifies Wheatland Township, Hillsdale County, Michigan.",
    },
    "holland-evening-sentinel__1960-09-16": {
        "city_name": "Holland",
        "state_abbr": "MI",
        "jurisdiction_level": "township",
        "target_pid6": "204703",
        "note": "Ordinance text identifies Holland Township, Ottawa County, Michigan; current Census of Governments continuation is Charter Township of Holland.",
    },
    "holland-evening-sentinel__1963-01-24": {
        "city_name": "Park",
        "state_abbr": "MI",
        "jurisdiction_level": "township",
        "target_pid6": "225624",
        "note": "Ordinance text identifies Park Township, Ottawa County, Michigan.",
    },
    "holland-evening-sentinel__1963-08-09": {
        "city_name": "Park",
        "state_abbr": "MI",
        "jurisdiction_level": "township",
        "target_pid6": "225624",
        "note": "Ordinance text identifies Park Township, Ottawa County, Michigan.",
    },
    "holland-evening-sentinel__1974-02-15": {
        "city_name": "Park",
        "state_abbr": "MI",
        "jurisdiction_level": "township",
        "target_pid6": "225624",
        "note": "Ordinance text identifies Park Township, Ottawa County, Michigan.",
    },
    "ironwood-daily-globe__1971-10-29": {
        "city_name": "Ironwood",
        "state_abbr": "MI",
        "jurisdiction_level": "township",
        "target_pid6": "106482",
        "note": "Ordinance header identifies Ironwood Township, Gogebic County, Michigan; current Census of Governments continuation is Charter Township of Ironwood.",
    },
    "ironwood-daily-globe__1985-10-08": {
        "city_name": "McMillan",
        "state_abbr": "MI",
        "jurisdiction_level": "township",
        "target_pid6": "106562",
        "note": "Ordinance header identifies McMillan Township, Ontonagon County, Michigan.",
    },
    "janesville-daily-gazette__1961-08-30": {
        "city_name": "Janesville",
        "state_abbr": "WI",
        "jurisdiction_level": "city",
        "target_pid6": "177224",
        "note": "Ordinance text identifies the City of Janesville, Wisconsin.",
    },
    "janesville-daily-gazette__1967-07-11": {
        "city_name": "Harmony",
        "state_abbr": "WI",
        "jurisdiction_level": "town",
        "target_pid6": "209912",
        "note": "Ordinance text identifies the Town of Harmony, Rock County, Wisconsin.",
    },
    "janesville-daily-gazette__1967-07-21": {
        "city_name": "Harmony",
        "state_abbr": "WI",
        "jurisdiction_level": "town",
        "target_pid6": "209912",
        "note": "Ordinance text identifies the Town of Harmony, Rock County, Wisconsin.",
    },
    "janesville-daily-gazette__1968-05-31": {
        "city_name": "Rock",
        "state_abbr": "WI",
        "jurisdiction_level": "county",
        "target_pid6": "177072",
        "note": "Enactment clause identifies Rock County, Wisconsin.",
    },
    "kokomo-tribune__1981-10-02": {
        "city_name": "Howard",
        "state_abbr": "IN",
        "jurisdiction_level": "county",
        "target_pid6": "163435",
        "note": "Ordinance title identifies Howard County, Indiana.",
    },
    "lawrence-daily-journal-world__1949-11-30": {
        "city_name": "Lawrence",
        "state_abbr": "KS",
        "jurisdiction_level": "city",
        "target_pid6": "184274",
        "note": "Ordinance text identifies the City of Lawrence, Kansas.",
    },
    "lebanon-daily-news__1974-04-26": {
        "city_name": "Swatara",
        "state_abbr": "PA",
        "jurisdiction_level": "township",
        "target_pid6": "174557",
        "note": "Ordinance text identifies Swatara Township, Lebanon County, Pennsylvania.",
    },
    "lowell-sun__1926-06-17": {
        "city_name": "Lowell",
        "state_abbr": "MA",
        "jurisdiction_level": "city",
        "target_pid6": "166449",
        "note": "Ordinance text identifies the City of Lowell; the newspaper context is Lowell, Massachusetts.",
    },
    "ludington-daily-news__1959-09-04": {
        "city_name": "Hamlin",
        "state_abbr": "MI",
        "jurisdiction_level": "township",
        "target_pid6": "167144",
        "note": "Ordinance title identifies Hamlin Township; the Ludington newspaper context places it in Mason County, Michigan.",
    },
    "ludington-daily-news__1961-02-24": {
        "city_name": "Summit",
        "state_abbr": "MI",
        "jurisdiction_level": "township",
        "target_pid6": "106534",
        "note": "Ordinance text identifies Summit Township, Mason County, Michigan.",
    },
    "ludington-daily-news__1963-04-30": {
        "city_name": "Summit",
        "state_abbr": "MI",
        "jurisdiction_level": "township",
        "target_pid6": "106534",
        "note": "Ordinance text identifies Summit Township, Mason County, Michigan.",
    },
    "madison-capital-times__1922-12-21": {
        "city_name": "Madison",
        "state_abbr": "WI",
        "jurisdiction_level": "city",
        "target_pid6": "209777",
        "note": "Ordinance title identifies Madison and the newspaper context is Madison, Wisconsin.",
    },
    "manitowoc-herald-times__1965-05-21": {
        "city_name": "Manitowoc",
        "state_abbr": "WI",
        "jurisdiction_level": "county",
        "target_pid6": "177069",
        "note": "Enactment clause identifies Manitowoc County, Wisconsin.",
    },
    "marshall-evening-chronicle__1957-03-07": {
        "city_name": "Lee",
        "state_abbr": "MI",
        "jurisdiction_level": "township",
        "target_pid6": "166908",
        "note": "Ordinance text identifies Lee Township in Calhoun County, Michigan.",
    },
    "marshall-evening-chronicle__1966-08-06": {
        "city_name": "Fredonia",
        "state_abbr": "MI",
        "jurisdiction_level": "township",
        "target_pid6": "166907",
        "note": "Ordinance adoption clause identifies Fredonia Township Board in Calhoun County, Michigan.",
    },
    "marshall-evening-chronicle__1973-03-15": {
        "city_name": "Marshall",
        "state_abbr": "MI",
        "jurisdiction_level": "city",
        "target_pid6": "166646",
        "note": "Ordinance text identifies the City of Marshall, Michigan.",
    },
    "middlebush-record__1955-07-29": {
        "city_name": "Franklin",
        "state_abbr": "NJ",
        "jurisdiction_level": "township",
        "target_pid6": "186570",
        "note": "Ordinance text identifies Franklin Township in Somerset County, New Jersey.",
    },
    "moab-times-independent__1964-08-20": {
        "city_name": "Grand",
        "state_abbr": "UT",
        "jurisdiction_level": "county",
        "target_pid6": "176435",
        "note": "Ordinance text identifies Grand County, Utah.",
    },
    "monitor-leader__1944-11-14": {
        "city_name": "Harrison",
        "state_abbr": "MI",
        "jurisdiction_level": "township",
        "target_pid6": "211747",
        "note": "Ordinance text identifies Harrison Township, Macomb County, Michigan; current Census of Governments continuation is Charter Township of Harrison.",
    },
    "mckinney-daily-courier-gazette__1946-10-19": {
        "city_name": "McKinney",
        "state_abbr": "TX",
        "jurisdiction_level": "city",
        "target_pid6": "187646",
        "note": "Ordinance text identifies the City of McKinney, Texas.",
    },
    "mckinney-daily-courier-gazette__1946-10-22": {
        "city_name": "McKinney",
        "state_abbr": "TX",
        "jurisdiction_level": "city",
        "target_pid6": "187646",
        "note": "Ordinance text identifies the City of McKinney, Texas.",
    },
    "new-castle-news__1926-01-05": {
        "city_name": "New Castle",
        "state_abbr": "PA",
        "jurisdiction_level": "city",
        "target_pid6": "111991",
        "note": "Ordinance text identifies the City of New Castle, Pennsylvania.",
    },
    "north-adams-transcript__1956-12-27": {
        "city_name": "Adams",
        "state_abbr": "MA",
        "jurisdiction_level": "town",
        "target_pid6": "183904",
        "note": "Ordinance text identifies the Town of Adams, Massachusetts.",
    },
    "oakland-tribune__1935-01-31": {
        "city_name": "Oakland",
        "state_abbr": "CA",
        "jurisdiction_level": "city",
        "target_pid6": "123093",
        "note": "Ordinance text identifies the City of Oakland, California.",
    },
    "ottumwa-courier__1992-05-29": {
        "city_name": "Wapello",
        "state_abbr": "IA",
        "jurisdiction_level": "county",
        "target_pid6": "164275",
        "note": "Ordinance title identifies Wapello County, Iowa.",
    },
    "penn-yan-chronicle-express__1961-09-21": {
        "city_name": "Middlesex",
        "state_abbr": "NY",
        "jurisdiction_level": "town",
        "target_pid6": "139405",
        "note": "Ordinance text identifies the Town of Middlesex, New York.",
    },
    "pulaski-southwest-times__1950-03-05": {
        "city_name": "Pulaski",
        "state_abbr": "VA",
        "jurisdiction_level": "county",
        "target_pid6": "176694",
        "note": "Enactment clause identifies Pulaski County, Virginia.",
    },
    "racine-journal-times__1949-07-06": {
        "city_name": "Racine",
        "state_abbr": "WI",
        "jurisdiction_level": "county",
        "target_pid6": "184234",
        "note": "Ordinance text identifies Racine County, Wisconsin.",
    },
    "racine-journal-times__1969-12-10": {
        "city_name": "Racine",
        "state_abbr": "WI",
        "jurisdiction_level": "county",
        "target_pid6": "184234",
        "note": "Ordinance text identifies Racine County, Wisconsin.",
    },
    "racine-journal-times__1976-02-09": {
        "city_name": "Racine",
        "state_abbr": "WI",
        "jurisdiction_level": "city",
        "target_pid6": "177216",
        "note": "Ordinance text identifies the City of Racine, Wisconsin.",
    },
    "rhinelander-daily-news__1970-09-24": {
        "city_name": "Oneida",
        "state_abbr": "WI",
        "jurisdiction_level": "county",
        "target_pid6": "212143",
        "note": "Enactment clause identifies Oneida County, Wisconsin.",
    },
    "rhinelander-new-north__1933-06-29": {
        "city_name": "Oneida",
        "state_abbr": "WI",
        "jurisdiction_level": "county",
        "target_pid6": "212143",
        "note": "Enactment clause identifies Oneida County, Wisconsin.",
    },
    "salisbury-daily-times__1970-10-11": {
        "city_name": "Wicomico",
        "state_abbr": "MD",
        "jurisdiction_level": "county",
        "target_pid6": "166369",
        "note": "Enactment clause identifies Wicomico County, Maryland.",
    },
    "saline-reporter__1977-12-07": {
        "city_name": "Saline",
        "state_abbr": "MI",
        "jurisdiction_level": "township",
        "target_pid6": "167330",
        "note": "Ordinance title identifies Saline Township; the newspaper context is Washtenaw County, Michigan.",
    },
    "san-benito-news__1954-04-15": {
        "city_name": "Cameron",
        "state_abbr": "TX",
        "jurisdiction_level": "county",
        "target_pid6": "187610",
        "note": "Enactment clause identifies Cameron County, Texas.",
    },
    "sandpoint-daily-bee__1977-06-22": {
        "city_name": "Bonner",
        "state_abbr": "ID",
        "jurisdiction_level": "county",
        "target_pid6": "124637",
        "note": "Ordinance title identifies Bonner County, Idaho.",
    },
    "sheboygan-press__1941-12-09": {
        "city_name": "Sheboygan",
        "state_abbr": "WI",
        "jurisdiction_level": "county",
        "target_pid6": "177074",
        "note": "Enactment clause identifies Sheboygan County, Wisconsin.",
    },
    "spirit-lake-beacon__1971-06-24": {
        "city_name": "Dickinson",
        "state_abbr": "IA",
        "jurisdiction_level": "county",
        "target_pid6": "164247",
        "note": "Enactment clause identifies Dickinson County, Iowa.",
    },
    "st-joseph-herald-press__1950-06-21": {
        "city_name": "St Joseph",
        "state_abbr": "MI",
        "jurisdiction_level": "township",
        "target_pid6": "201929",
        "note": "Ordinance text identifies Saint Joseph Township in Berrien County, Michigan; current Census of Governments continuation is Charter Township of St Joseph.",
    },
    "state-center-enterprise__1956-08-30": {
        "city_name": "Marshall",
        "state_abbr": "IA",
        "jurisdiction_level": "county",
        "target_pid6": "126550",
        "note": "Enactment clause identifies Marshall County, Iowa.",
    },
    "stevens-point-daily-journal__1977-09-20": {
        "city_name": "Plover",
        "state_abbr": "WI",
        "jurisdiction_level": "village",
        "target_pid6": "115097",
        "note": "Ordinance title identifies the Village of Plover, Portage County, Wisconsin.",
    },
    "traverse-city-record-eagle__1969-04-18": {
        "city_name": "Peninsula",
        "state_abbr": "MI",
        "jurisdiction_level": "township",
        "target_pid6": "201935",
        "note": "Ordinance title identifies Peninsula Township, Grand Traverse County, Michigan.",
    },
    "traverse-city-record-eagle__1971-08-18": {
        "city_name": "Garfield",
        "state_abbr": "MI",
        "jurisdiction_level": "township",
        "target_pid6": "193506",
        "note": "Published extraction names Paradise Township, but the ordinance header and enactment clause clearly identify Garfield Township, Grand Traverse County, Michigan.",
    },
    "twin-falls-times-news__1991-10-22": {
        "city_name": "Twin Falls",
        "state_abbr": "ID",
        "jurisdiction_level": "county",
        "target_pid6": "124642",
        "note": "Enactment clause identifies Twin Falls County, Idaho.",
    },
    "valparaiso-vidette-messenger__1951-06-09": {
        "city_name": "Valparaiso",
        "state_abbr": "IN",
        "jurisdiction_level": "city",
        "target_pid6": "126072",
        "note": "Ordinance text identifies the City of Valparaiso in Porter County, Indiana.",
    },
}
